language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

env:
  matrix:
    - SPRING_VERSION=4.1.0.RELEASE
    - SPRING_VERSION=4.1.1.RELEASE
    - SPRING_VERSION=4.1.2.RELEASE
    - SPRING_VERSION=4.1.3.RELEASE
    - SPRING_VERSION=4.1.4.RELEASE
    - SPRING_VERSION=4.1.5.RELEASE
    - SPRING_VERSION=4.1.6.RELEASE
    - SPRING_VERSION=4.1.7.RELEASE
    - SPRING_VERSION=4.1.8.RELEASE
    - SPRING_VERSION=4.1.9.RELEASE
    - SPRING_VERSION=4.2.0.RELEASE
    - SPRING_VERSION=4.2.1.RELEASE
    - SPRING_VERSION=4.2.2.RELEASE
    - SPRING_VERSION=4.2.3.RELEASE
    - SPRING_VERSION=4.2.4.RELEASE
    - SPRING_VERSION=4.2.5.RELEASE
    - SPRING_VERSION=4.2.6.RELEASE
    - SPRING_VERSION=4.2.7.RELEASE
    - SPRING_VERSION=4.2.8.RELEASE
    - SPRING_VERSION=4.2.9.RELEASE
    - SPRING_VERSION=4.3.0.RELEASE
    - SPRING_VERSION=4.3.1.RELEASE
    - SPRING_VERSION=4.3.2.RELEASE
    - SPRING_VERSION=4.3.3.RELEASE
    - SPRING_VERSION=4.3.4.RELEASE
    - SPRING_VERSION=4.3.5.RELEASE
    - SPRING_VERSION=4.3.6.RELEASE
    - SPRING_VERSION=4.3.7.RELEASE

script: ./mvnw clean verify -D spring.version=$SPRING_VERSION

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
